import { chromium, expect } from '@playwright/test';
import { mkdir, readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
const root=process.cwd();const pack=path.join(root,'tmp/sample-pack');
await mkdir('screenshots',{recursive:true});await mkdir('output',{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
console.log('Browser version:',browser.version());
const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true});
const page=await context.newPage();const errors=[];const external=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('request',req=>{if(!req.url().startsWith('http://127.0.0.1:5173')&&!req.url().startsWith('blob:')&&!req.url().startsWith('data:'))external.push(req.url());});
await page.goto('http://127.0.0.1:5173/');
await page.screenshot({path:'screenshots/01-workspace.png',fullPage:true});
await page.getByLabel('Load tender',{exact:true}).setInputFiles(path.join(pack,'requirements.json'));
await expect(page.getByTestId('requirement-R01').locator('.badge')).toHaveText('Missing');
await expect(page.getByTestId('requirement-R06').locator('.badge')).toHaveText('Not provided');
await expect(page.getByRole('button',{name:'Generate package',exact:true})).toBeDisabled();
const all=await readdir(path.join(pack,'documents'));
await page.getByLabel('Upload PDFs',{exact:true}).setInputFiles(all.map(f=>path.join(pack,'documents',f)));
await expect(page.getByLabel('Upload PDFs',{exact:true})).toBeEnabled({timeout:30000});
await expect(page.locator('.file-row')).toHaveCount(10);
await expect(page.getByRole('alert')).toContainText('Only PDF documents');
await expect(page.locator('.file-list .badge')).toHaveCount(2);
async function match(id,name){const select=page.getByTestId(`requirement-${id}`).locator('select');const opt=select.locator('option').filter({hasText:name}).first();await select.selectOption(await opt.getAttribute('value'));}
await match('R01','trade_license_2025.pdf');
await expect(page.getByTestId('requirement-R01').locator('.badge')).toHaveText('Expiry date needed');
await page.getByLabel('Expiry for Trade License',{exact:true}).fill('2025-06-30');
await expect(page.getByTestId('requirement-R01').locator('.badge')).toHaveText('Expired');
await page.getByLabel('Expiry for Trade License',{exact:true}).fill('2026-10-20');
await expect(page.getByTestId('requirement-R01').locator('.badge')).toHaveText('OK');
await match('R01','trade_license_2026.pdf');
await expect(page.getByLabel('Expiry for Trade License',{exact:true})).toHaveValue('');
await page.getByLabel('Expiry for Trade License',{exact:true}).fill('2027-06-30');
await match('R02','03_tin_certificate.pdf');await match('R03','04_vat_certificate.pdf');
await match('R04','bank_solvency.pdf');await page.getByLabel('Expiry for Bank Solvency Certificate',{exact:true}).fill('2026-12-31');
await match('R05','experience_cert.pdf');
await expect(page.getByTestId('requirement-R06').locator('option').filter({hasText:'experience_cert (1).pdf'})).toBeDisabled();
await match('R08','02_technical_proposal.pdf');await match('R09','01_financial_proposal.pdf');await match('R10','scan_0042.pdf');
await expect(page.getByRole('button',{name:'Generate package',exact:true})).toBeEnabled();
// Same file moves atomically, then can be restored.
await match('R06','03_tin_certificate.pdf');
await expect(page.getByTestId('requirement-R02').locator('.badge')).toHaveText('Missing');
await match('R02','03_tin_certificate.pdf');
await expect(page.getByTestId('requirement-R06').locator('.badge')).toHaveText('Not provided');
await page.locator('h1').click();
await page.screenshot({path:'screenshots/02-document-statuses.png',fullPage:true});
const csvDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export checklist CSV',exact:true}).click();const csv=await csvDownload;expect(csv.suggestedFilename()).toBe('T-2026-0417_Checklist.csv');await csv.saveAs('tmp/checklist.csv');expect(await readFile('tmp/checklist.csv','utf8')).toContain('Not provided');
await page.getByRole('button',{name:'বাংলা',exact:true}).click();
await expect(page.locator('html')).toHaveAttribute('lang','bn');
await expect(page.getByTestId('requirement-R01').locator('h3')).toHaveText('ট্রেড লাইসেন্স');
await expect(page.getByTestId('requirement-R01').locator('input')).toHaveValue('2027-06-30');
await expect(page.getByTestId('requirement-R01').locator('.badge')).toHaveText('ঠিক আছে');
await page.screenshot({path:'screenshots/03-bangla-statuses.png',fullPage:true});
const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'প্যাকেজ তৈরি করুন',exact:true}).click();
const download=await downloadEvent;expect(download.suggestedFilename()).toBe('T-2026-0417_Package.pdf');await download.saveAs('output/'+download.suggestedFilename());
await expect(page.getByRole('status')).toContainText('ডাউনলোড');
await page.getByRole('button',{name:'EN',exact:true}).click();
await page.getByRole('button',{name:'Remove 03_tin_certificate.pdf',exact:true}).click();
await expect(page.getByTestId('requirement-R02').locator('.badge')).toHaveText('Missing');
await expect(page.getByRole('button',{name:'Generate package',exact:true})).toBeDisabled();
await page.getByLabel('Upload PDFs',{exact:true}).setInputFiles({name:'damaged.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7 broken')});
await expect(page.getByLabel('Upload PDFs',{exact:true})).toBeEnabled();await expect(page.getByRole('alert')).toContainText('damaged');
await page.getByLabel('Load tender',{exact:true}).setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{')});
await expect(page.getByRole('alert')).toContainText('not valid JSON');await expect(page.getByTestId('requirement-R01')).toBeVisible();
// Fresh unseen tender with scrambled order and a changed deadline.
const unseen=JSON.parse(await readFile(path.join(pack,'requirements.json'),'utf8'));unseen.tender.tender_id='UNSEEN-OTHER';unseen.requirements.reverse();
await page.getByLabel('Load tender',{exact:true}).setInputFiles({name:'unseen.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(unseen))});
await expect(page.locator('.requirement').first()).toHaveAttribute('data-testid','requirement-R01');await expect(page.locator('.file-row')).toHaveCount(0);
const bytes=await readFile(path.join(pack,'documents/03_tin_certificate.pdf'));
await page.getByLabel('Upload PDFs',{exact:true}).setInputFiles(Array.from({length:31},(_,i)=>({name:`file-${i}.pdf`,mimeType:'application/pdf',buffer:bytes})));
await expect(page.getByLabel('Upload PDFs',{exact:true})).toBeEnabled({timeout:45000});await expect(page.locator('.file-row')).toHaveCount(30);await expect(page.getByRole('alert')).toContainText('limit is 30');
// Size rejection without allocating or parsing an oversized PDF in the app.
await page.getByLabel('Load tender',{exact:true}).setInputFiles(path.join(pack,'requirements.json'));
await page.getByLabel('Upload PDFs',{exact:true}).setInputFiles({name:'too-large.pdf',mimeType:'application/pdf',buffer:Buffer.alloc(50_000_001)});
await expect(page.getByRole('alert')).toContainText('total limit is 50 MB');await expect(page.locator('.file-row')).toHaveCount(0);
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'বাংলা',exact:true}).click();
await page.screenshot({path:'screenshots/04-mobile.png',fullPage:true});
expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
expect(errors).toEqual([]);expect(external).toEqual([]);
console.log('Browser acceptance passed: sample workflow, 16-page download, dates, duplicates, reassignment, removal, bilingual state, malformed inputs, unseen order, 30-file/50-MB limits, mobile overflow, zero external requests.');
await browser.close();
