import type { Language } from './types';
const en = {
  exportCsv:'Export checklist CSV',
  builder:'PACKAGE BUILDER', private:'Your files stay on this device', workspace:'TENDER WORKSPACE', heading:'A complete bid starts here.', intro:'Check your documents. Build a submission-ready package.',
  load:'Load tender', change:'Change tender', uploadStep:'Upload documents', matchStep:'Match & check', generateStep:'Generate package', workflow:'Workflow', deadline:'Submission deadline',
  checklist:'Document checklist', requirements:'requirements', hint:'Match each requirement to a PDF, then check its validity.', first:'First, load your tender.', chooseHelp:'Choose your requirements.json file to see the documents you need and their submission order.', choose:'Choose requirements.json', local:'Requirements and documents are processed on your device.',
  required:'Required', optional:'Optional', expiryCheck:'Expiry check', select:'Select a document', fileFor:'File for', move:'move here', duplicateUsed:'duplicate in use', undo:'Undo match for', expiryFor:'Expiry for', expiry:'Expiry date', validAfter:'Valid on or after', noRequirements:'This tender has no document requirements.',
  missing:'Missing', not_provided:'Not provided', expiry_needed:'Expiry date needed', expired:'Expired', ok:'OK',
  documents:'Your documents', processing:'Processing documents…', drop:'Drop PDFs here or browse files', filesHere:'PDF documents go here', limits:'PDF only · Up to 30 files · 50 MB total', upload:'Upload PDFs', ofLimit:'of 50 MB', pages:'pages', page:'page', remove:'Remove', duplicate:'Duplicate content',
  final:'FINAL PACKAGE', ready:'Your package is ready.', ordered:'Everything in the right order.', documentsReady:'documents ready', issues:'issues to resolve', checked:'All requirements checked. Your PDF will include an English cover and numbered pages.', packageHelp:'An English cover, your documents, and page numbers. All in one PDF.', generate:'Generate package', generating:'Building your package…', generated:'Package downloaded. Your submission is ready.', onDevice:'Generated entirely on your device', privacy:'Private by design. No document uploads to a server.', product:'Tender Document Package Builder', language:'Interface language',
  invalid_json:'This file is not valid JSON.', invalid_schema:'Invalid requirements field. Check the file structure and dates.', read_error:'Could not read this file. Please try again.', not_pdf:'Only PDF documents are accepted.', bad_pdf:'This PDF is damaged or unsupported. Please use a valid copy.', locked_pdf:'This PDF is password-protected. Upload an unlocked copy.', file_limit:'The limit is 30 PDF files. Remove a file before adding more.', size_limit:'The total limit is 50 MB (50,000,000 bytes). Remove files to make room.', duplicate_match:'An identical copy is already matched to another requirement. Undo that match first.', unknown_file:'That file is no longer available.', generation_error:'The package could not be created. Check your files and try again.', blocked:'Resolve the checklist issues before generating.', pdf_text_error:'A cover field contains characters not supported by the English PDF font.',
  changeTitle:'Change the tender?', changeHelp:'Loading another tender clears the current documents, matches, and expiry dates.', cancel:'Keep working', confirm:'Choose another tender', close:'Dismiss message',
} as const;
const bn: Record<keyof typeof en,string> = {
  exportCsv:'চেকলিস্ট CSV ডাউনলোড',
  builder:'প্যাকেজ বিল্ডার', private:'আপনার ফাইল এই ডিভাইসেই থাকে', workspace:'দরপত্রের কর্মক্ষেত্র', heading:'সম্পূর্ণ দরপত্র তৈরির শুরু এখানেই।', intro:'নথি যাচাই করুন। জমা দেওয়ার উপযোগী প্যাকেজ তৈরি করুন।',
  load:'দরপত্র খুলুন', change:'দরপত্র পরিবর্তন', uploadStep:'নথি যোগ করুন', matchStep:'মিলিয়ে যাচাই', generateStep:'প্যাকেজ তৈরি', workflow:'কাজের ধাপ', deadline:'জমা দেওয়ার শেষ তারিখ',
  checklist:'নথির চেকলিস্ট', requirements:'টি চাহিদা', hint:'প্রতিটি চাহিদার সঙ্গে একটি PDF মিলিয়ে তার বৈধতা যাচাই করুন।', first:'প্রথমে দরপত্র খুলুন।', chooseHelp:'প্রয়োজনীয় নথি ও জমা দেওয়ার ক্রম দেখতে requirements.json ফাইলটি বেছে নিন।', choose:'requirements.json বেছে নিন', local:'চাহিদা ও নথি আপনার ডিভাইসেই প্রক্রিয়া করা হয়।',
  required:'আবশ্যিক', optional:'ঐচ্ছিক', expiryCheck:'মেয়াদ যাচাই', select:'একটি নথি বেছে নিন', fileFor:'যে নথির ফাইল', move:'এখানে সরান', duplicateUsed:'একই নথি ব্যবহৃত', undo:'মিল বাতিল করুন', expiryFor:'যে নথির মেয়াদ', expiry:'মেয়াদ শেষের তারিখ', validAfter:'এই তারিখ বা তার পর পর্যন্ত বৈধ', noRequirements:'এই দরপত্রে কোনো নথির চাহিদা নেই।',
  missing:'অনুপস্থিত', not_provided:'দেওয়া হয়নি', expiry_needed:'মেয়াদ শেষের তারিখ দিন', expired:'মেয়াদোত্তীর্ণ', ok:'ঠিক আছে',
  documents:'আপনার নথি', processing:'নথি যাচাই করা হচ্ছে…', drop:'PDF এখানে টানুন বা ফাইল বেছে নিন', filesHere:'PDF নথি এখানে যোগ করুন', limits:'শুধু PDF · সর্বোচ্চ ৩০টি ফাইল · মোট ৫০ MB', upload:'PDF যোগ করুন', ofLimit:'/ ৫০ MB', pages:'পৃষ্ঠা', page:'পৃষ্ঠা', remove:'সরান', duplicate:'একই বিষয়বস্তুর নকল',
  final:'চূড়ান্ত প্যাকেজ', ready:'আপনার প্যাকেজ প্রস্তুত।', ordered:'সব নথি সঠিক ক্রমে।', documentsReady:'নথি প্রস্তুত', issues:'টি সমস্যা সমাধান করুন', checked:'সব চাহিদা যাচাই হয়েছে। PDF-এ ইংরেজি প্রচ্ছদ ও পৃষ্ঠা নম্বর থাকবে।', packageHelp:'ইংরেজি প্রচ্ছদ, আপনার নথি ও পৃষ্ঠা নম্বর—সব এক PDF-এ।', generate:'প্যাকেজ তৈরি করুন', generating:'প্যাকেজ তৈরি হচ্ছে…', generated:'প্যাকেজ ডাউনলোড হয়েছে। আপনার দরপত্র প্রস্তুত।', onDevice:'সম্পূর্ণ আপনার ডিভাইসে তৈরি', privacy:'আপনার গোপনীয়তা সুরক্ষিত। সার্ভারে কোনো নথি পাঠানো হয় না।', product:'দরপত্র নথি প্যাকেজ বিল্ডার', language:'ইন্টারফেসের ভাষা',
  invalid_json:'ফাইলটি সঠিক JSON নয়।', invalid_schema:'চাহিদার তথ্য সঠিক নয়। ফাইলের কাঠামো ও তারিখ যাচাই করুন।', read_error:'ফাইলটি পড়া যায়নি। আবার চেষ্টা করুন।', not_pdf:'শুধু PDF নথি গ্রহণ করা হয়।', bad_pdf:'PDF-টি ক্ষতিগ্রস্ত বা অসমর্থিত। সঠিক কপি ব্যবহার করুন।', locked_pdf:'PDF-টি পাসওয়ার্ড দিয়ে সুরক্ষিত। আনলক করা কপি দিন।', file_limit:'সর্বোচ্চ ৩০টি PDF রাখা যাবে। নতুন ফাইলের আগে একটি সরান।', size_limit:'মোট সীমা ৫০ MB (৫০,০০০,০০০ বাইট)। কিছু ফাইল সরান।', duplicate_match:'একই নথির আরেকটি কপি অন্য চাহিদায় ব্যবহৃত। আগে সেই মিল বাতিল করুন।', unknown_file:'ফাইলটি আর পাওয়া যাচ্ছে না।', generation_error:'প্যাকেজ তৈরি করা যায়নি। ফাইলগুলো যাচাই করে আবার চেষ্টা করুন।', blocked:'প্যাকেজ তৈরির আগে চেকলিস্টের সমস্যা সমাধান করুন।', pdf_text_error:'প্রচ্ছদের কিছু অক্ষর ইংরেজি PDF ফন্টে সমর্থিত নয়।',
  changeTitle:'দরপত্র পরিবর্তন করবেন?', changeHelp:'অন্য দরপত্র খুললে বর্তমান নথি, মিল ও মেয়াদের তারিখ মুছে যাবে।', cancel:'কাজ চালিয়ে যান', confirm:'অন্য দরপত্র বেছে নিন', close:'বার্তা বন্ধ করুন',
};
export type TextKey = keyof typeof en;
export const translator = (language: Language) => (key: TextKey): string => (language === 'bn' ? bn : en)[key];
export const messageText = (language: Language, code: string) => code in en ? translator(language)(code as TextKey) : translator(language)('read_error');
